print("Welcome to the memory birthday chart!")
name1 = input("Merlin, What is your birthday?")
name2 = input("Valentina, What is your birthday?")
name3 = input("Gaurav, What is your birthday?")
name4 = input("Akshay, What is your birthday?")
name5 = input("Shon, What is your birthday?")
print("Here are there birthdays:\n")
print("Merlin's birthday is", name1)
print("Valentina's birthday is", name2)
print("Gaurav's birthday is", name3)
print("Akshay's birthday is", name4)
print("Shon's birthday is", name5)